### ISSUE TITLE
Can you upgrade version ?

### ISSUE THREAD

**Issue by satels** [pymorphy2-fork/pymorphy2#23]
0.9.1 -- is prev version

**Comment by insolor** [comment]
I'm not sure if I will continue supporting of this project. Someday I'll probably publish a release (or not).

At the moment you can just use https://github.com/no-plagiarism/pymorphy3, it contains fixes from this repo.

**Comment by insolor** [comment]
Short answer: just use https://github.com/no-plagiarism/pymorphy3.

You don't need to fork and patch the version yourself. There is an active fork, even published on pypi, just use it.
